### PR TITLE
feat(sidekick): content root button

### PR DESCRIPTION
**Pull request by rofe**

### CODE REVIEW

**Comment by ispykenny** [comment]
Hey @rofe,

This is awesome. One thing I'm noticing is that this goes to the global pages root, rather than the page content root.

So if we are on https://pages.adobe.com/creativecloud/en/ete/how-adobe-apps-work-together/

The "Content root" button would take you to `google-drive-root/creativecloud/en/ete/`

Let me know if there's any issue with this.
Thank you!

**Comment by rofe** [comment]
OK, now I get it! 😆 

@tripodsan could we add the `folderURL` of a document to the JSON report?

**Comment by rofe** [comment]
> So if we are on https://pages.adobe.com/creativecloud/en/ete/how-adobe-apps-work-together/
> 
> The "Content root" button would take you to `google-drive-root/creativecloud/en/ete/`

@ispykenny: FYI In your example,`ete` would be the grandparent, not the parent folder: URLs ending in `/` are indentical to `/index`, so in that case, the correct parent would actually be `how-adobe-apps-work-together`.

**Comment by rofe** [comment]
@ispykenny this is ready to go!

**Comment by ispykenny** [comment]
This is great. Thank you @rofe  🎉

**Pull request merged**
