### PR TITLE
convert components/embeds to blocks

### PR DESCRIPTION
**Pull request by maxakuru**
I hope you enjoy this comically large PR

Branch:
https://hlx3-embeds--pages--adobe.hlx3.page/creativecloud/en/ete/how-adobe-apps-work-together/
 https://hlx3-embeds--pages--adobe.hlx3.page/illustrator/en/tl/thr-layout-home/
 https://hlx3-embeds--pages--adobe.hlx3.page/stock/en/advocates/
  https://hlx3-embeds--pages--adobe.hlx3.page/stock/en/advocates/artist-development-fund
  https://hlx3-embeds--pages--adobe.hlx3.page/stock/en/advocates/celebration-of-self
  https://hlx3-embeds--pages--adobe.hlx3.page/premiere/en/speechtotext/
  https://hlx3-embeds--pages--adobe.hlx3.page/general/en/inclusive/feedback/
  https://hlx3-embeds--pages--adobe.hlx3.page/photoshop/en/feedback
  https://hlx3-embeds--pages--adobe.hlx3.page/character/en/body-tracker
  https://hlx3-embeds--pages--adobe.hlx3.page/ihearttech/en/
  https://hlx3-embeds--pages--adobe.hlx3.page/lightroom/en/wg/feedback-wg
  https://hlx3-embeds--pages--adobe.hlx3.page/photoshop/en/prerelease-api/
  
Compare to:
https://pages.adobe.com/creativecloud/en/ete/how-adobe-apps-work-together/
 https://pages.adobe.com/illustrator/en/tl/thr-layout-home/
 https://pages.adobe.com/stock/en/advocates/
  https://pages.adobe.com/stock/en/advocates/artist-development-fund
  https://pages.adobe.com/stock/en/advocates/celebration-of-self
  https://pages.adobe.com/premiere/en/speechtotext/
  https://pages.adobe.com/general/en/inclusive/feedback/
  https://pages.adobe.com/photoshop/en/feedback
  https://pages.adobe.com/character/en/body-tracker
  https://pages.adobe.com/ihearttech/en/
  https://pages.adobe.com/lightroom/en/wg/feedback-wg
  https://pages.adobe.com/photoshop/en/prerelease-api/

### CODE REVIEW

**Review by davidnuescheler — COMMENTED** [review]
generally this looks great ... i am sseing issues/errors here:

https://hlx3-embeds--pages--adobe.hlx3.page/stock/en/advocates/
https://hlx3-embeds--pages--adobe.hlx3.page/stock/en/advocates/artist-development-fund
https://hlx3-embeds--pages--adobe.hlx3.page/stock/en/advocates/celebration-of-self

and some layout issues here:
https://hlx3-embeds--pages--adobe.hlx3.page/character/en/body-tracker

**Comment by davidnuescheler** [comment]
definitely looks a lot better... congrats:

these seem to be missing the main body though...
https://hlx3-embeds--pages--adobe.hlx3.page/stock/en/advocates/
https://hlx3-embeds--pages--adobe.hlx3.page/stock/en/advocates/celebration-of-self

the form doesn't seem to be pulled up here:
https://hlx3-embeds--pages--adobe.hlx3.page/general/en/inclusive/feedback/
https://hlx3-embeds--pages--adobe.hlx3.page/lightroom/en/wg/feedback-wg

this one looks different as well, which could be an indication that something goes wrong...
https://hlx3-embeds--pages--adobe.hlx3.page/photoshop/en/feedback

**Comment by davidnuescheler** [comment]
i tested all the links and they look very good, i also added:
https://hlx3-embeds--pages--adobe.hlx3.page/general/en/blog/

works well...
@ispykenny IIRC this one needed a query param to work:
https://hlx3-embeds--pages--adobe.hlx3.page/photoshop/en/feedback
i don't remember anymore what that was so it would be great if you could test that as well.

**Review by davidnuescheler — APPROVED** [review]

**Comment by ispykenny** [comment]
> i tested all the links and they look very good, i also added:
> https://hlx3-embeds--pages--adobe.hlx3.page/general/en/blog/
> 
> works well...
> @ispykenny IIRC this one needed a query param to work:
> https://hlx3-embeds--pages--adobe.hlx3.page/photoshop/en/feedback
> i don't remember anymore what that was so it would be great if you could test that as well.

Yep! This one did need a param which I believe it was
`feedback?f=5FAFFB1D-624C-492A-AEB4-CFE35D4E9238&s=4`

the s value being the value of the rating`&s=valueofRating`

**Pull request merged**
